import { Agent, QuickAction, ActivityItem } from '@/types';

export const AGENTS: Agent[] = [
  {
    id: 'agent-research',
    name: 'Research Agent',
    type: 'research',
    status: 'idle',
    description: 'Web research, summarization, and information gathering',
    icon: '🔍',
    color: '#4d7cff',
    tasksCompleted: 147,
    lastActive: new Date(Date.now() - 300000).toISOString(),
  },
  {
    id: 'agent-coding',
    name: 'Coding Agent',
    type: 'coding',
    status: 'active',
    description: 'Code generation, debugging, and optimization',
    icon: '💻',
    color: '#34d399',
    tasksCompleted: 234,
    lastActive: new Date().toISOString(),
  },
  {
    id: 'agent-automation',
    name: 'Automation Agent',
    type: 'automation',
    status: 'idle',
    description: 'Browser control, app automation, and workflow execution',
    icon: '⚡',
    color: '#fb923c',
    tasksCompleted: 89,
    lastActive: new Date(Date.now() - 600000).toISOString(),
  },
  {
    id: 'agent-productivity',
    name: 'Productivity Agent',
    type: 'productivity',
    status: 'idle',
    description: 'Task management, scheduling, and organization',
    icon: '📊',
    color: '#a855f7',
    tasksCompleted: 312,
    lastActive: new Date(Date.now() - 120000).toISOString(),
  },
  {
    id: 'agent-vision',
    name: 'Vision Agent',
    type: 'vision',
    status: 'idle',
    description: 'Screen analysis, OCR, object detection, and face recognition',
    icon: '👁️',
    color: '#f472b6',
    tasksCompleted: 56,
    lastActive: new Date(Date.now() - 1800000).toISOString(),
  },
  {
    id: 'agent-memory',
    name: 'Memory Agent',
    type: 'memory',
    status: 'active',
    description: 'Context storage, semantic search, and preference learning',
    icon: '🧠',
    color: '#00f0ff',
    tasksCompleted: 1024,
    lastActive: new Date().toISOString(),
  },
];

export const QUICK_ACTIONS: QuickAction[] = [
  { id: 'qa-1', label: 'Search Web', description: 'Research a topic online', icon: '🌐', command: 'search', agentType: 'research', shortcut: 'Ctrl+S' },
  { id: 'qa-2', label: 'Generate Code', description: 'Write code for a task', icon: '💻', command: 'code', agentType: 'coding', shortcut: 'Ctrl+G' },
  { id: 'qa-3', label: 'Open Browser', description: 'Control browser actions', icon: '🌍', command: 'browser', agentType: 'automation', shortcut: 'Ctrl+B' },
  { id: 'qa-4', label: 'Analyze Screen', description: 'Read and analyze display', icon: '📸', command: 'screenshot', agentType: 'vision', shortcut: 'Ctrl+P' },
  { id: 'qa-5', label: 'Create Task', description: 'Add a new task to queue', icon: '📋', command: 'task', agentType: 'productivity', shortcut: 'Ctrl+T' },
  { id: 'qa-6', label: 'Recall Memory', description: 'Search past conversations', icon: '🧠', command: 'recall', agentType: 'memory', shortcut: 'Ctrl+M' },
  { id: 'qa-7', label: 'Voice Mode', description: 'Start voice interaction', icon: '🎙️', command: 'voice', agentType: 'productivity' },
  { id: 'qa-8', label: 'Run Workflow', description: 'Execute automation script', icon: '⚡', command: 'workflow', agentType: 'automation' },
];

export const SAMPLE_ACTIVITY: ActivityItem[] = [
  {
    id: 'act-1',
    type: 'agent',
    title: 'Coding Agent activated',
    description: 'Debugging Python script — resolved 3 syntax errors',
    timestamp: new Date(Date.now() - 30000).toISOString(),
    icon: '💻',
    color: '#34d399',
  },
  {
    id: 'act-2',
    type: 'memory',
    title: 'Memory updated',
    description: 'Stored user preference: dark theme, voice enabled',
    timestamp: new Date(Date.now() - 120000).toISOString(),
    icon: '🧠',
    color: '#00f0ff',
  },
  {
    id: 'act-3',
    type: 'voice',
    title: 'Voice command processed',
    description: '"Open YouTube and play lo-fi music"',
    timestamp: new Date(Date.now() - 300000).toISOString(),
    icon: '🎙️',
    color: '#a855f7',
  },
  {
    id: 'act-4',
    type: 'automation',
    title: 'Browser automation complete',
    description: 'Opened 3 tabs, filled form, submitted report',
    timestamp: new Date(Date.now() - 600000).toISOString(),
    icon: '⚡',
    color: '#fb923c',
  },
  {
    id: 'act-5',
    type: 'task',
    title: 'Research task completed',
    description: 'Summarized 5 articles on quantum computing',
    timestamp: new Date(Date.now() - 900000).toISOString(),
    icon: '🔍',
    color: '#4d7cff',
  },
  {
    id: 'act-6',
    type: 'system',
    title: 'System health check',
    description: 'All services operational — latency: 45ms',
    timestamp: new Date(Date.now() - 1200000).toISOString(),
    icon: '✅',
    color: '#34d399',
  },
];

export const API_BASE_URL = process.env.NEXT_PUBLIC_API_URL || 'http://localhost:8000';
export const WS_URL = process.env.NEXT_PUBLIC_WS_URL || 'ws://localhost:8000/ws';
